// Command amsonia-local runs the complete local Amsonia Core stack without
// putting generated database credentials in source control or shell history.
package main

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"

	"golang.org/x/term"
)

const localEnvironmentPath = ".amsonia/local.env"

func main() {
	if err := run(context.Background(), os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string) error {
	if len(args) != 1 || (args[0] != "up" && args[0] != "down" && args[0] != "status") {
		return errors.New("usage: amsonia-local up | down | status")
	}
	if _, err := os.Stat("compose.yaml"); err != nil {
		return errors.New("run this command from the Amsonia Core repository root")
	}
	if _, err := exec.LookPath("docker"); err != nil {
		return errors.New("Docker with the Compose plugin is required")
	}
	if args[0] == "up" {
		created, err := ensureLocalEnvironment(localEnvironmentPath)
		if err != nil {
			return err
		}
		if created {
			fmt.Fprintf(os.Stdout, "Generated local infrastructure credentials in %s (mode 0600).\n", localEnvironmentPath)
		}
		if err := compose(ctx, "up", "--build", "--detach"); err != nil {
			return err
		}
		state, err := composeOutput(ctx, "exec", "-T", "api", "/usr/local/bin/amsonia", "admin-status")
		if err != nil {
			return fmt.Errorf("check administrator status: %w", err)
		}
		switch strings.TrimSpace(state) {
		case "configured":
			// Nothing to do. This makes repeated `make demo` calls idempotent.
		case "missing":
			if !term.IsTerminal(int(syscall.Stdin)) {
				return errors.New("the stack is running, but first-time administrator bootstrap requires an interactive terminal; rerun `make demo` locally")
			}
			fmt.Fprintln(os.Stdout, "Create the one-time local administrator. The password is read without echo and is never stored by this command.")
			if err := composeInteractive(ctx, "exec", "api", "/usr/local/bin/amsonia", "bootstrap-admin"); err != nil {
				return fmt.Errorf("bootstrap local administrator: %w", err)
			}
		default:
			return fmt.Errorf("unexpected administrator status %q", strings.TrimSpace(state))
		}
		fmt.Fprintln(os.Stdout, "Amsonia Core is ready at http://127.0.0.1:8080")
		fmt.Fprintln(os.Stdout, "API health: http://127.0.0.1:8080/health")
		return nil
	}
	if _, err := os.Stat(localEnvironmentPath); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return errors.New("local environment not found; run `make demo` first")
		}
		return err
	}
	if args[0] == "down" {
		return composeInteractive(ctx, "down")
	}
	return composeInteractive(ctx, "ps")
}

func ensureLocalEnvironment(path string) (bool, error) {
	if info, err := os.Stat(path); err == nil {
		if !info.Mode().IsRegular() {
			return false, fmt.Errorf("%s is not a regular file", path)
		}
		if info.Mode().Perm()&0o077 != 0 {
			return false, fmt.Errorf("%s must not be readable by group or other users", path)
		}
		return false, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return false, fmt.Errorf("create local state directory: %w", err)
	}
	if err := os.Chmod(filepath.Dir(path), 0o700); err != nil {
		return false, fmt.Errorf("secure local state directory: %w", err)
	}
	runtimeSecret, err := randomBytes(32)
	if err != nil {
		return false, err
	}
	maintenanceSecret, err := randomBytes(32)
	if err != nil {
		return false, err
	}
	ownerPassword, err := randomToken(32)
	if err != nil {
		return false, err
	}
	runtimePassword, err := randomToken(32)
	if err != nil {
		return false, err
	}
	maintenancePassword, err := randomToken(32)
	if err != nil {
		return false, err
	}
	content := strings.Join([]string{
		"# Generated by cmd/amsonia-local. Local development only; do not commit.",
		"AMSONIA_POSTGRES_OWNER_PASSWORD=" + ownerPassword,
		"AMSONIA_POSTGRES_RUNTIME_PASSWORD=" + runtimePassword,
		"AMSONIA_POSTGRES_MAINTENANCE_PASSWORD=" + maintenancePassword,
		"AMSONIA_RUNTIME_SECRET_HEX=" + hex.EncodeToString(runtimeSecret),
		"AMSONIA_MAINTENANCE_SECRET_HEX=" + hex.EncodeToString(maintenanceSecret),
		"AMSONIA_TENANT_BINDING_SECRET=" + base64.RawURLEncoding.EncodeToString(runtimeSecret),
		"AMSONIA_DATABASE_DSN=postgres://amsonia_runtime:" + runtimePassword + "@127.0.0.1:55432/amsonia_core?sslmode=disable",
		"AMSONIA_POSTGRES_PORT=55432",
		"AMSONIA_WEB_PORT=8080",
		"",
	}, "\n")
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return false, fmt.Errorf("create local environment: %w", err)
	}
	if _, err := file.WriteString(content); err != nil {
		_ = file.Close()
		return false, fmt.Errorf("write local environment: %w", err)
	}
	if err := file.Close(); err != nil {
		return false, fmt.Errorf("close local environment: %w", err)
	}
	return true, nil
}

func randomBytes(size int) ([]byte, error) {
	value := make([]byte, size)
	if _, err := rand.Read(value); err != nil {
		return nil, fmt.Errorf("generate local credential: %w", err)
	}
	return value, nil
}

func randomToken(size int) (string, error) {
	value, err := randomBytes(size)
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(value), nil
}

func composeArgs(arguments ...string) []string {
	return append([]string{"compose", "--env-file", localEnvironmentPath, "--file", "compose.yaml", "--file", "compose.local.yaml"}, arguments...)
}

func compose(ctx context.Context, arguments ...string) error {
	command := exec.CommandContext(ctx, "docker", composeArgs(arguments...)...)
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return fmt.Errorf("docker compose %s: %w", arguments[0], err)
	}
	return nil
}

func composeInteractive(ctx context.Context, arguments ...string) error {
	command := exec.CommandContext(ctx, "docker", composeArgs(arguments...)...)
	command.Stdin = os.Stdin
	command.Stdout = os.Stdout
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		return fmt.Errorf("docker compose %s: %w", arguments[0], err)
	}
	return nil
}

func composeOutput(ctx context.Context, arguments ...string) (string, error) {
	command := exec.CommandContext(ctx, "docker", composeArgs(arguments...)...)
	output, err := command.Output()
	if err == nil {
		return string(output), nil
	}
	var exitError *exec.ExitError
	if errors.As(err, &exitError) {
		return "", fmt.Errorf("docker compose %s: %s", arguments[0], strings.TrimSpace(string(exitError.Stderr)))
	}
	return "", fmt.Errorf("docker compose %s: %w", arguments[0], err)
}
